mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('restaurant_menu.urls', 'restaurant_menu'), namespace="restaurant_menu")),
    path('', include(('users.urls', 'users'), namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('item/<int:item_id>', views.details, name='details'),
    path('item/add', views.add_item, name='add_item'),
    path('item/<int:item_id>/edit', views.edit_item, name='edit_item'),
    path('item/<int:item_id>/delete', views.delete_item, name='delete_item'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),

]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User


MEAL_TYPE = (
    ("starters", "Starters"),
    ("main_course", "Main Course"),
    ("salads", "Salads"),
    ("drinks", "Drinks"),
    ("sides", "Sides"),
)

STATUS = (
    (0, "Unavailable"),
    (1, "Available"),
    (2, "Cooking"),
)


class MenuItem(models.Model):
    meal = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=1000)
    meal_type = models.CharField(max_length=200, choices=MEAL_TYPE)
    status = models.IntegerField(choices=STATUS, default=1)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    image = models.CharField(max_length=500, default="https://encrypted-tbn0.gstatic.com/images?q=tbn"
                                                     ":ANd9GcS5PTsuRj6pjDdRDNqaC27k705rxveiomd99w&s")
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.meal} {self.status}"

users/models.py
from django.db import models
from django.contrib.auth.models import User

GENDER = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
)

ROLES = (
    ('manager', 'Manager'),
    ('cashier', 'Cashier'),
    ('chef', 'Chef'),
    ('waiter', 'Waiter'),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default_profile-pic.jpg', upload_to='profile_pictures/')
    gender = models.CharField(max_length=100, choices=GENDER)
    role = models.CharField(max_length=150, choices=ROLES)
    location = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.user.username}'s profile"

restaurant_menu/forms.py
from django import forms
from .models import MenuItem


class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ['meal', 'description', 'meal_type', 'status', 'price', 'image', 'author']

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

restaurant_menu/views.py
from django.shortcuts import render, redirect
from .models import MenuItem, MEAL_TYPE
from django.contrib.auth.decorators import login_required
from .forms import MenuItemForm
from django.contrib import messages


def index(request):
    item_list = MenuItem.objects.all()
    context = {
        'item_list': item_list,
        'item_types': MEAL_TYPE,
    }
    return render(request, "index.html", context)


def details(request, item_id):
    item = MenuItem.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, "details.html", context)


@login_required
def add_item(request):
    if request.method == 'POST':
        form = MenuItemForm(request.POST)
        if form.is_valid():
            form.save()
            name = form.cleaned_data['author'].username
            item = form.cleaned_data['meal']
            messages.success(request, message=f"Hi {name}, The item {item} is added in the menu!")

    else:
        form = MenuItemForm()
    return render(request, 'add_item.html', {'form': form, })


@login_required
def edit_item(request, item_id):
    instance = MenuItem.objects.get(pk=item_id)

    if request.method == "POST":
        form = MenuItemForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('restaurant_menu:home')

    else:
        form = MenuItemForm(instance=instance)
    return render(request, 'edit_item.html', {'form': form, })


@login_required
def delete_item(request, item_id):
    item = MenuItem.objects.get(pk=item_id)

    if request.method == "POST":
        item.delete()
        return redirect("restaurant_menu:home")

    else:
        return render(request, 'delete_item.html', {'item': item,})

users/views.py
from django.shortcuts import render
from .forms import SignupForm
from django.contrib import messages
from django import views
from django.contrib.auth import logout


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.add_message(request, level=200, message=f"Hi {username}! Your account is created successfully.")

    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


class LogoutView(views.View):
    def get(self, request):
        logout(request)
        return render(request, 'logout.html')


def profile(request):
    return render(request, 'profile.html')

restaurant_menu/templates/add_item.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}

    <h4 class="mb-3">Enter the Item Details:</h4>

    {{ form.as_p }}

    <div>
        <button class="btn btn-success" type="submit">Add</button>
    </div>
</form>

{% if messages %}
    {% for message in messages %}
        <div>
            <h4>{{ message }}</h4>
        </div>
    {% endfor %}
    <a class="btn btn-warning" href="{% url 'restaurant_menu:home' %}">Back to Menu</a>
{% endif %}


{% endblock %}

restaurant_menu/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <title>The Best Restaurant</title>
</head>

<body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'restaurant_menu:home' %}">The Best Restaurant</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'restaurant_menu:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-success" href="{% url 'restaurant_menu:add_item' %}">Add Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </nav>


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</body>
</html>

restaurant_menu/templates/delete_item.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}

    <h4 class="mb-3">Are you sure to delete {{ item.meal }} ?</h4>
    <img class="card mb-3" src="{{ item.image }}" alt="{{ item.meal }} image" height="250"/>
    <div class="row">
        <div class="col-md-1 justify-content-start">
            <button class="btn btn-danger" type="submit">Delete</button>
        </div>
        <div class="col-md-2 justify-content-start">
            <a class="btn btn-secondary" href="{% url 'restaurant_menu:home' %}">Cancel</a>
        </div>
    </div>

</form>

{% endblock %}

restaurant_menu/templates/details.html
{% extends 'base.html' %}
{% block content %}

<div class="card" style="width: 36rem;">
    <img class="card-img-top" src="{{ item.image }}" alt="{{ item.meal }} image">
    <div class="card-body">
        <h1 class="card-title">{{ item.meal }}</h1>
        <h4 class="card-text">{{ item.description }}</h4>
        <h3 class="card-text">Price: ${{ item.price }}</h3>
    </div>
    <div class="card-body">
        <a class="card-link btn btn-success" href="{% url 'restaurant_menu:home' %}">Back to Menu</a>
    </div>

</div>

{% endblock %}

restaurant_menu/templates/edit_item.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}

    <h4 class="mb-3">Edit the Item Details:</h4>

    {{ form.as_p }}

    <div>
        <button class="btn btn-success" type="submit">Save</button>
    </div>
</form>

{% endblock %}

restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}

{% for it in item_types %}
    <br/>
    <h1 class="mb-4">{{ it.1 }}</h1>
    <div class="row">
        {% for item in item_list %}
            {% if item.meal_type == it.0 %}
                <div class="col-md-6 mb-3">
                    <div class="card h-100 d-flex flex-column">
                        <div class="row no-gutters flex-grow-1">
                            <div class="col-4">
                                <img class="card-img" src="{{ item.image }}" alt="{{ item.meal }} image" height="200px"/>
                            </div>
                            <div class="col-8 d-flex flex-column">
                                <div class="card-body">
                                    <h3 class="card-title">{{ item.meal }}</h3>
                                    <h4 class="card-text">${{ item.price }}</h4>
                                </div>
                                <div class="mt-auto d-flex justify-content-end p-2">
                                    <a class="btn btn-primary btn-sm ml-3" href="{% url 'restaurant_menu:details' item.id %}">More Details</a>
                                    {% if user.is_authenticated %}
                                        <a class="btn btn-secondary btn-sm ml-3" href="{% url 'restaurant_menu:edit_item' item.id %}">Edit</a>
                                        <a class="btn btn-danger btn-sm ml-3" href="{% url 'restaurant_menu:delete_item' item.id %}">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

{% endblock %}

users/templates/base_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <title>The Best Restaurant</title>
</head>
<body>
    <div class="container">

        {% block content %}

        {% endblock %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</body>
</html>

users/templates/login.html
{% extends 'base_users.html' %}
{% block content %}

<h3 class="mt-4 mb-4">Enter your credentials:</h3>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <div>
        <button class="btn btn-success" type="submit">Login</button>
    </div>
</form>

<div>
    <a href="{% url 'restaurant_menu:home' %}">Continue without logging in!</a>
</div>

{% endblock %}

users/templates/logout.html
{% extends 'base_users.html' %}
{% block content %}

<h1> You have logged out. Thanks for visiting!!! </h1>

<div>
    <a href="{% url 'users:login' %}" >Visit Again!</a>
</div>

{% endblock %}

users/templates/profile.html
{% extends 'base_users.html' %}
{% block content %}
<h1 class="mt-4 mb-4">Profile</h1>
<img src="{{ user.profile.image.url }}" height="250 px"/>
<h2>{{ user.username }}</h2>
<h3 class="mt-4 mb-4">{{ user.profile.role }}</h3>
<h3 class="mt-4 mb-4">Location: {{ user.profile.location }}</h3>

{% endblock %}

users/templates/signup.html
{% extends 'base_users.html' %}
{% block content %}
<h3 class="mt-4 mb-4">Enter valid info below to register: </h3>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <div>
        <button class="btn btn-success" type="submit">Sign Up</button>
    </div>
</form>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success mb-3 mt-4" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    <div>
        <a class="btn btn-success" href="{% url 'users:login' %}">Login Now!</a>
    </div>

{% endif %}

{% endblock %}